### ISSUE TITLE
Add basic MIPS programs .(Arithmetic, array ops, etc)

### ISSUE THREAD

**Issue by Mithunitp** [Mithunitp/Mips-Statistics-Guide#2]
Objective:
To cover fundamentals of MIPS assembly language.
Comment the program you want to add and request to be assigned.
Upload code to MIPSbasics folder and create PR.

**Comment by DeepanshuGOYAL05** [comment]
Hey, in which language these to be added?

**Comment by Mithunitp** [comment]
@DeepanshuGOYAL05 Use MIPS assembly language.
